(cl:in-package V2X_Integration-msg)
(cl:export '(HEADER-VAL
          HEADER
          FB_KOPFROTATION_GIER_GUETE-VAL
          FB_KOPFROTATION_GIER_GUETE
          FB_KOPFPOSITION_Z_GUETE-VAL
          FB_KOPFPOSITION_Z_GUETE
          FB_KOPFPOSITION_Y_GUETE-VAL
          FB_KOPFPOSITION_Y_GUETE
          FB_KOPFPOSITION_X_GUETE-VAL
          FB_KOPFPOSITION_X_GUETE
          FB_KOPFROTATION_GIER-VAL
          FB_KOPFROTATION_GIER
          FB_KOPFPOSITION_Z-VAL
          FB_KOPFPOSITION_Z
          FB_KOPFPOSITION_Y-VAL
          FB_KOPFPOSITION_Y
          FB_KOPFPOSITION_X-VAL
          FB_KOPFPOSITION_X
))