# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from V2X_Integration/SARA_06_Msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class SARA_06_Msg(genpy.Message):
  _md5sum = "2d6f91f1b10aaef29935d4bdfc80abae"
  _type = "V2X_Integration/SARA_06_Msg"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
uint16 SARA_06_CRC
uint8 SARA_06_BZ
float32 SARA_Accel_X_010
float32 SARA_Accel_Y_010
float32 SARA_Omega_Z_010
uint8 SARA_CF_Accel_X_010
uint8 SARA_CF_Accel_Y_010
uint8 SARA_CF_Omega_Z_010

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','SARA_06_CRC','SARA_06_BZ','SARA_Accel_X_010','SARA_Accel_Y_010','SARA_Omega_Z_010','SARA_CF_Accel_X_010','SARA_CF_Accel_Y_010','SARA_CF_Omega_Z_010']
  _slot_types = ['std_msgs/Header','uint16','uint8','float32','float32','float32','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,SARA_06_CRC,SARA_06_BZ,SARA_Accel_X_010,SARA_Accel_Y_010,SARA_Omega_Z_010,SARA_CF_Accel_X_010,SARA_CF_Accel_Y_010,SARA_CF_Omega_Z_010

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SARA_06_Msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.SARA_06_CRC is None:
        self.SARA_06_CRC = 0
      if self.SARA_06_BZ is None:
        self.SARA_06_BZ = 0
      if self.SARA_Accel_X_010 is None:
        self.SARA_Accel_X_010 = 0.
      if self.SARA_Accel_Y_010 is None:
        self.SARA_Accel_Y_010 = 0.
      if self.SARA_Omega_Z_010 is None:
        self.SARA_Omega_Z_010 = 0.
      if self.SARA_CF_Accel_X_010 is None:
        self.SARA_CF_Accel_X_010 = 0
      if self.SARA_CF_Accel_Y_010 is None:
        self.SARA_CF_Accel_Y_010 = 0
      if self.SARA_CF_Omega_Z_010 is None:
        self.SARA_CF_Omega_Z_010 = 0
    else:
      self.header = std_msgs.msg.Header()
      self.SARA_06_CRC = 0
      self.SARA_06_BZ = 0
      self.SARA_Accel_X_010 = 0.
      self.SARA_Accel_Y_010 = 0.
      self.SARA_Omega_Z_010 = 0.
      self.SARA_CF_Accel_X_010 = 0
      self.SARA_CF_Accel_Y_010 = 0
      self.SARA_CF_Omega_Z_010 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_HB3f3B().pack(_x.SARA_06_CRC, _x.SARA_06_BZ, _x.SARA_Accel_X_010, _x.SARA_Accel_Y_010, _x.SARA_Omega_Z_010, _x.SARA_CF_Accel_X_010, _x.SARA_CF_Accel_Y_010, _x.SARA_CF_Omega_Z_010))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.SARA_06_CRC, _x.SARA_06_BZ, _x.SARA_Accel_X_010, _x.SARA_Accel_Y_010, _x.SARA_Omega_Z_010, _x.SARA_CF_Accel_X_010, _x.SARA_CF_Accel_Y_010, _x.SARA_CF_Omega_Z_010,) = _get_struct_HB3f3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_HB3f3B().pack(_x.SARA_06_CRC, _x.SARA_06_BZ, _x.SARA_Accel_X_010, _x.SARA_Accel_Y_010, _x.SARA_Omega_Z_010, _x.SARA_CF_Accel_X_010, _x.SARA_CF_Accel_Y_010, _x.SARA_CF_Omega_Z_010))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.SARA_06_CRC, _x.SARA_06_BZ, _x.SARA_Accel_X_010, _x.SARA_Accel_Y_010, _x.SARA_Omega_Z_010, _x.SARA_CF_Accel_X_010, _x.SARA_CF_Accel_Y_010, _x.SARA_CF_Omega_Z_010,) = _get_struct_HB3f3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_HB3f3B = None
def _get_struct_HB3f3B():
    global _struct_HB3f3B
    if _struct_HB3f3B is None:
        _struct_HB3f3B = struct.Struct("<HB3f3B")
    return _struct_HB3f3B
